// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGByGypclQhU2xZpEjXF7cydNDULnWoRs',
    appId: '1:491888535430:web:278842e20eb64acc8bae07',
    messagingSenderId: '491888535430',
    projectId: 'social-media-app-mitch',
    authDomain: 'social-media-app-mitch.firebaseapp.com',
    storageBucket: 'social-media-app-mitch.appspot.com',
    measurementId: 'G-564DEW9S8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYg_MD_ZaLib1jOgzfv6UnMwIL_TY5Bak',
    appId: '1:491888535430:android:ae6a9b7a9c9076bd8bae07',
    messagingSenderId: '491888535430',
    projectId: 'social-media-app-mitch',
    storageBucket: 'social-media-app-mitch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPveL8Fm7KPD5dJz1chph9fpKaF8bWdJE',
    appId: '1:491888535430:ios:42beca8e550a42708bae07',
    messagingSenderId: '491888535430',
    projectId: 'social-media-app-mitch',
    storageBucket: 'social-media-app-mitch.appspot.com',
    iosBundleId: 'com.example.socialMediaAppMitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPveL8Fm7KPD5dJz1chph9fpKaF8bWdJE',
    appId: '1:491888535430:ios:42beca8e550a42708bae07',
    messagingSenderId: '491888535430',
    projectId: 'social-media-app-mitch',
    storageBucket: 'social-media-app-mitch.appspot.com',
    iosBundleId: 'com.example.socialMediaAppMitch',
  );
}
